#pragma once

#define LUAHIDAPI_VERSION_MAJOR ${LIB_VERSION_MAJOR}
#define LUAHIDAPI_VERSION_MINOR ${LIB_VERSION_MINOR}
#define LUAHIDAPI_VERSION_PATCH ${LIB_VERSION_PATCH}
#define LUAHIDAPI_VERSION "${LIBRARY_VERSION}"

